# Generated by Django 5.2.5 on 2025-08-07 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jockey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('track_configuration', models.CharField(choices=[('L', 'Left Handed'), ('R', 'Right Handed'), ('S', 'Straight')], max_length=1)),
                ('track_condition', models.CharField(choices=[('F', 'Fast'), ('Z', 'Frozen'), ('G', 'Good'), ('H', 'Heavy'), ('M', 'Muddy'), ('S', 'Sloppy'), ('L', 'Slow'), ('W', 'Wet Fast'), ('FM', 'Firm'), ('HD', 'Hard'), ('SF', 'Soft'), ('YL', 'Yielding'), ('ST', 'Standard'), ('HR', 'Harsh')], max_length=2)),
                ('classification', models.CharField(choices=[('G1', 'Grade 1'), ('G2', 'Grade 2'), ('G3', 'Grade 3'), ('L', 'Listed'), ('H', 'Handicap'), ('M', 'Maiden'), ('O', 'Other')], max_length=2)),
                ('season', models.CharField(choices=[('SP', 'Spring'), ('SU', 'Summer'), ('FA', 'Fall'), ('WI', 'Winter')], max_length=2)),
                ('track_length', models.PositiveIntegerField(help_text='Length in meters')),
                ('track_surface', models.CharField(choices=[('D', 'Dirt'), ('T', 'Turf'), ('S', 'Synthetic'), ('O', 'Other')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Racehorse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('age', models.IntegerField()),
                ('breed', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('is_winner', models.BooleanField(default=False)),
                ('jockey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='horses.jockey')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horses.race')),
                ('racehorse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horses.racehorse')),
            ],
        ),
    ]
